version: '3.9'

services:
  geo_plot_analyzer_postgresql:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "45432:5432"
    networks:
      - geo_plot_analyzer_net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  geo_plot_analyzer_api:
    environment:
      - Database__ConnectionString=${Database__ConnectionString}
      - Main__PublicUrl=${Main__PublicUrl}
      - Log__Level=${Log__Level}
      - Swagger__Enabled=${Swagger__Enabled}
    ports:
      - "10000:8080"
    networks:
      - geo_plot_analyzer_net

networks:
  geo_plot_analyzer_net:
    driver: bridge

volumes:
  postgres-data: